// Drives the real game in headless Chromium and saves screenshots: node scripts/shot-game.mjs <url> <outdir>
import { chromium } from '@playwright/test';
import fs from 'node:fs';
const url = process.argv[2] ?? 'http://localhost:5190/';
const out = process.argv[3] ?? '.';
fs.mkdirSync(out, { recursive: true });
const exe = ['/opt/pw-browsers/chromium-1194/chrome-linux/chrome', '/opt/pw-browsers/chromium'].find((p) => fs.existsSync(p) && fs.statSync(p).isFile());
const browser = await chromium.launch({ executablePath: exe, args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', (e) => errors.push(String(e)));
const shot = (n) => page.screenshot({ path: `${out}/${n}.png` });
await page.goto(url + '?laps=1&autopilot');
await page.waitForFunction(() => window.__game?.state.screen === 'title', null, { timeout: 120000 });
await page.waitForTimeout(1500); await shot('01-title');
await page.keyboard.press('Enter'); await page.waitForTimeout(800); await shot('02-menu');
await page.click('[data-testid=btn-quick-race]'); await page.waitForTimeout(1500); await shot('03-character');
await page.click('[data-testid=char-lupin]'); await page.waitForTimeout(800);
await page.click('[data-testid=btn-confirm-character]'); await page.waitForTimeout(800); await shot('04-track');
await page.click('[data-testid=track-chicago]');
await page.waitForFunction(() => window.__game?.state.screen === 'race', null, { timeout: 120000 });
await page.waitForTimeout(2000); await shot('05-countdown');
await page.waitForTimeout(6000); await shot('06-racing');
await page.waitForTimeout(6000); await shot('07-racing2');
console.log('state', JSON.stringify(await page.evaluate(() => window.__game.state)));
await page.waitForFunction(() => window.__game?.state.screen === 'results', null, { timeout: 400000, polling: 1000 });
await page.waitForTimeout(3000); await shot('08-results');
console.log('errors', errors.length, errors.slice(0, 10));
await browser.close();
